package tech.techsete.witetec_sdk.enums;

public enum WebhookEventType {
    TRANSACTION_PAID,
    TRANSACTION_PENDING,
    TRANSACTION_FAILED,
    TRANSACTION_DISPUTE,
    TRANSACTION_REFUNDED,
    TRANSACTION_CHARGEDBACK,

    WITHDRAWAL_PENDING,
    WITHDRAWAL_APPROVED,
    WITHDRAWAL_REJECTED,
    WITHDRAWAL_PROCESSING,
    WITHDRAWAL_PAID,
    WITHDRAWAL_FAILED,
    WITHDRAWAL_REFUNDED,
    WITHDRAWAL_CANCELED,
    WITHDRAWAL_BLOCKED
}
